[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "chromium", "glib", "nss", "atk", "cups", "dbus", "libdrm", "libxcb", "libxkbcommon"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node index.js"
